CREATE SEQUENCE "typecho_collection_seq";

CREATE TABLE IF NOT EXISTS "typecho_contents" (  "id" INT NOT NULL DEFAULT nextval('typecho_collection_seq'),
  "category" VARCHAR(10) NOT NULL DEFAULT 'subject',
  "class" INT NULL DEFAULT NULL,
  "type" VARCHAR(20) NULL DEFAULT NULL,
  "name" VARCHAR(100) NOT NULL,
  "name_cn" VARCHAR(100) NULL DEFAULT NULL,
  "image" VARCHAR(200) NULL DEFAULT NULL,
  "ep_count" INT NULL DEFAULT NULL,
  "publisher" VARCHAR(50) NULL DEFAULT NULL,
  "published" INT NULL DEFAULT NULL,
  "source" VARCHAR(20) NOT NULL DEFAULT 'Collection',
  "source_id" VARCHAR(50) NULL DEFAULT NULL,
  "parent" INT NOT NULL DEFAULT '0',
  "parent_order" INT NOT NULL DEFAULT '0',
  "parent_label" VARCHAR(10) NULL DEFAULT NULL,
  "grade" INT NOT NULL DEFAULT '0',
  "status" CHAR(7) NOT NULL DEFAULT 'wish',
  "time_start" INT NULL DEFAULT NULL,
  "time_finish" INT NULL DEFAULT NULL,
  "time_touch" INT NOT NULL,
  "ep_status" INT NULL DEFAULT NULL,
  "rate" INT NOT NULL DEFAULT '0',
  "tags" VARCHAR(200) NULL DEFAULT NULL,
  "comment" TEXT NULL DEFAULT NULL,
  "note" TEXT NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);