CREATE TABLE IF NOT EXISTS typecho_collection ( "id" INTEGER NOT NULL PRIMARY KEY, 
"category" varchar(10) default 'subject',
"class" int(1) default NULL,
"type" varchar(20) default NULL,
"name" varchar(100) NOT NULL,
"name_cn" varchar(100) default NULL,
"image" varchar(200) default NULL,
"ep_count" int(5) default NULL,
"ep_start" int(5) default NULL,
"author" varchar(50) default NULL,
"publisher" varchar(50) default NULL,
"published" int(10) default NULL,
"source" varchar(20) NOT NULL default 'Collection',
"source_id" varchar(50) default NULL,
"media_link" varchar(255) default NULL,
"parent" int NOT NULL default '0',
"parent_order" int(5) NOT NULL default '0',
"parent_label" varchar(10) default NULL,
"grade" int(1) NOT NULL default '0',
"status" char(7) NOT NULL default 'wish',
"time_start" int(10) default NULL,
"time_finish" int(10) default NULL,
"time_touch" int(10) NOT NULL,
"ep_status" int(4) default NULL,
"rate" int(2) NOT NULL default '0',
"tags" varchar(200) default NULL,
"comment" text,
"note" text );
